config/routes.rb
Rails.application.routes.draw do
  root to: 'spaces#home'

  devise_for :users
  resources :users, only: [:edit, :update]
  get 'my_account', to: 'users#show'

  get 'spaces', to: "spaces#index"

  resources :spaces, except: [:delete] do
    resources :bookings, except: [:new, :index, :show] do
      resources :reviews, except: [:new, :index, :show]
    end
  end
end

app/models/space.rb
class Space < ApplicationRecord
  validates :name, :address, :category, :price, presence: true
  mount_uploader :cover_image, PhotoUploader
  belongs_to :user, foreign_key: 'owner_id'
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search,
                   against: [:category],
                   using: {
                    tsearch: { prefix: true }
                   }
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :search, :show]
  before_action :set_space, only: [:show, :edit, :update]

  def home
    @spaces = Space.all.order(created_at: :desc).limit(5)
  end

  def index
    if params[:place].nil? || (params[:place] == "" && params[:cat] == "")
      @spaces = Space.all.order(created_at: :desc)
    elsif params[:place] == "" || params[:place].nil?
      @spaces = Space.search(params[:cat])
    elsif params[:cat] == "" || params[:cat].nil?
      @spaces = Space.near(params[:place], 50)
    else
      @spaces = Space.search(params[:cat]) & Space.near(params[:place], 50)
    end
    # @markers = @spaces.map do |space|
    #   {
    #     lat: space.latitude,
    #     lng: space.longitude
    #   }
    # end

    # @geocoded_spaces = Space.geocoded
    @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { space: space }),
        image_url: helpers.asset_url('marker.png')
      }

    end
  end

  def show
    @markers = [{
        lat: @space.latitude,
        lng: @space.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { space: @space }),
        image_url: helpers.asset_url('marker.png')
      }]
    @booking = Booking.new
    @reviewed_booking = Booking.where(user: current_user, space: @space).last
    @review = Review.new
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    if @space.save
      redirect_to space_path(@space)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @space.update(space_params)
      redirect_to space_path(@space)
    else
      render 'edit'
    end
  end

  private

  def space_params
    params.require(:space).permit(:name, :address, :description, :category, :price, :cover_image, :video_url, :published)
  end

  def set_space
    @space = Space.find(params[:id])
  end

  def empty_query(string)

  end

end

app/views/spaces/_info_window.html.erb
<% if space.cover_image.file.nil? %>
  <img src=<%= asset_path("placeholder.jpg") %>>
<% else %>
  <%= cl_image_tag space.cover_image %>
<% end %>

<h3><%= link_to(space.name, space_path(space)) %></h3>
<p><%= space.address %></p>

app/views/spaces/_map.html.erb
<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/spaces/_space-form.html.erb
<%= simple_form_for [@space] do |f| %>
  <% if @space.errors.any? %>
    <div class="alert alert-danger">
      <h4>Warning! You have some errors:</h4>
        <ul>
          <% @space.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :category %>
    <%= f.input :cover_image %>
    <%= f.input :published %>
  </div>

  <div class="form-actions btn-primary btn">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/spaces/_space-list.html.erb
<div class="index-container">
<div class="search-cards">

  <div class="card-grid-index">

<form id="spaces-search-bar" method="get">
  <input placeholder="Find a city to party" id="space_address" name="place">
  <button class="btn btn-primary" type="submit">Search</button>
</form>

    <div class="row">
      <% sorted!(@spaces).each do |space| %>
          <div class="col-lg-6 col-md-12 col-sm-12">
            <div class="card-trip">
              <% if space.cover_image.file.nil? %>
                <img src=<%= asset_path("placeholder.jpg") %>>
              <% else %>
                <%= cl_image_tag space.cover_image %>
              <% end %>
            <% unless average_rating(aggregate_reviews(space)).zero? %>

            <h2> <%= average_rating(aggregate_reviews(space))%> <%= '⭑' * average_rating(aggregate_reviews(space))  %></h2>
            <% end %>
              <div class="card-text">
                <div class="card-info">
                  <h2>
                    <%= link_to(space.name, space_path(space)) %>
                  </h2>
                   <p><%= space.category %></p>
                </div>
                <h3>📍<%= space.address %></h3>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>



</div>

<div class="map-index">

    <div
      id="map"
      style="mapbox://styles/mapbox/dark-v10"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
 </div>

</div>

app/views/spaces/_space_form.html.erb
<%= simple_form_for @space do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :category, collection: available_categories %>
  <%= f.input :price %>
  <%= f.input :cover_image %>
  <%= f.input :cover_image_cache, as: :hidden %>
  <%= f.input :video_url %>
  <%= f.input :published %>
  <%= f.submit class: 'btn btn-primary mb-2' %>
<% end %>

app/views/spaces/edit.html.erb
<%= render 'spaces/space_form' %>

app/views/spaces/home.html.erb
 <video autoplay muted loop id="myVideo">
<source src=<%= asset_path('party.mp4') %> type=video/mp4>
</video>

  <div id="hero">
<!--      <video autoplay muted loop id="myVideo">
      <source src="assets/party.mp4" type="video/mp4"> -->
    <div class="col-lg-6 col-md-6 col-sm-12" id="hero-box">
      <div id="hero-text">
        <h1>Find unique places to party hardy.</h1>
        <h3>On space-x, you will find the best places to host your next crazy party. Discover the hottest spots in your area.</h3>
      </div>
      <div class="search-form">
          <form action="spaces" method="get" id="home-search-form">
              <div class="form-group">
                <label for="space_address">Where</label>
                <input type="search" class="form-control" id="space_address" placeholder="Anywhere" name="place">
              </div>

              <div class="form-group">
                <label for="cat">What</label>
                <select class="form-control select required" name="cat" id="space_category">
                <option value=""></option>
                <option value="concert hall">concert hall</option>
                <option value="movie theater">movie theater</option>
                <option value="house">house</option>
                <option value="cave">cave</option>
                <option value="museum">museum</option>
                <option value="art gallery">art gallery</option>
                <option value="aquarium">aquarium</option></select>
              </div>

              <input type="Submit" class="btn btn-primary">
          </form>
      </div>
    </div>
  </div>
<footer></footer>

app/views/spaces/index.html.erb
<% if @spaces.empty? %>

<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> Sorry, there is no space matching your criteria, why not find another place to party or look into our whole collection?.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

  <% @spaces = Space.all %>
  <% @markers = @spaces.map do |space| %>
    <% {lat: space.latitude,lng: space.longitude} %>
  <% end %>
  <%= render 'spaces/space-list' %>
<% else %>
  <%= render 'spaces/space-list' %>
<% end %>

app/views/spaces/new.html.erb
<div class="submit-background">
  <div class="signup-container">
    <div class="pages-container">
      <div class="signup-form-heading">
        <h2>Add a new space</h2>
      </div>
        <%= render 'spaces/space_form' %>
      </div>
  </div>
</div>

app/views/spaces/show.html.erb
<% if @space.cover_image.file.nil? %>
  <% cover_img = "#{asset_path('placeholder.jpg')}" %>
<% else %>
  <% cover_img = "#{cl_image_path @space.cover_image}" %>
<% end %>

<div class="header-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= cover_img %> )">
  <div class="show-header">
    <h1><%= @space.name %></h1>
    <p>📌<%= @space.address %></p>
  </div>
  <div class="price-tag">
    <h3><%= @space.price %>,00 €</h3>
  </div>
</div>


<div class="pages-container">

  <div class="action-bar">
  <%= link_to("Go back", spaces_path, class: 'btn btn-outline-secondary')  %>
  </div>

  <div class="show-details">

  <div class="column-left">

      <div class="show-box" id="about">
        <h2>About this venue</h2>
        <p class="description"> <%= @space.description %></p>
      </div>

      <% unless aggregate_reviews(@space).empty? %>
        <div class="show-box">
          <h2>Reviews</h2>
          <% aggregate_reviews(@space).each do |review| %>
              <p>
                <%='⭐️' *review.rating %> - <%= review.title %> - <%= review.content %>
                <% if user_signed_in? %>
                  <% if Booking.find(review.booking_id).user_id == @user.id %>
                    <%= link_to("Edit", edit_space_booking_review_path(@space, Booking.find(review.booking_id), review)) %>
                    <%= link_to space_booking_review_path(@space, Booking.find(review.booking_id), review), method: :delete, data: {confirm: "Are you sure?"} do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </p>
          <% end %>
        </div>
      <% end %>

      <div class="show-box">
        <h2>Location</h2>
        <%= render 'spaces/map' %>
      </div>

      <% unless @reviewed_booking.nil? %>
        <div class="show-box" id="review-form">
          <h2>Review your experience</h2>
          <%= render 'reviews/review-form' %>
        </div>
      <% end %>
  </div>

  <div class="column-right">
    <% converted_url = url_converter(@space) %>
    <% unless @space.video_url.nil? %>
        <div class="show-box" id="place-video">
        <iframe width="100%" height="350px" src='<%= converted_url %>' frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    <% end %>

    <% unless @reviewed_booking.nil? %>
      <div class="show-box" id="review-form">
        <h2>Ads from our friends</h2>
        <iframe src="https://giphy.com/embed/7uqIGMyoNr3y0" width="480" height="365" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
        <a style="width:200px; margin-left:150px; " href="https://dodgebnb.herokuapp.com" target="_blank" class="btn btn-primary"/>Book party pet 🎉🐰</a>
      </div>
    <% end %>

    <div class="sticky-booking" id="bookings">
      <div class="show-box">
        <h2>Book now</h2>
        <h3><%= @space.price %>,00 €</h3>
        <%= render 'bookings/booking-form' %>

        <% @space.bookings.future.where(user:current_user).order(date: :asc).each do |booking| %>
          <p style="font-size: 1em;">
            You have an upcoming booking on <%= booking.date %>.
            <%= link_to("Edit", edit_space_booking_path(@space, booking)) %>
            <%= link_to space_booking_path(@space, booking), method: :delete, data: {confirm: "Are you sure?"} do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </p>
        <% end %>

        <% unless @space.bookings.past.where(user: current_user).empty? %>
          <h4>Past bookings</h4>
        <% end %>
        <% @space.bookings.past.where(user: current_user).order(date: :desc).each do |booking| %>
          <p>
            You booked this space on <%= booking.date %>,
            <%= link_to('review it', space_path(@space, anchor: 'review-form'))%>.</br>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

</div>