config/routes.rb
Rails.application.routes.draw do
  root to: 'spaces#home'

  devise_for :users
  resources :users, only: [:edit, :update]
  get 'my_account', to: 'users#show'

  get 'spaces', to: "spaces#index"

  resources :spaces, except: [:delete] do
    resources :bookings, except: [:new, :index, :show] do
      resources :reviews, except: [:new, :index, :show]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :phone_number, presence: true
  mount_uploader :avatar, PhotoUploader
  has_many :spaces, foreign_key: 'owner_id', dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @spaces = Space.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to my_account_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone_number, :email, :password, :avatar)
  end

  def set_user
    @user = current_user
  end

end

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :phone_number %>
  <%= f.input :email %>
  <%= f.input :avatar %>
  <%= f.input :avatar_cache, as: :hidden %>
  <%= f.submit class: 'btn btn-primary mb-2' %>
<% end %>

<%= link_to("Back", my_account_path) %>

app/views/users/show.html.erb
<div class="account-container">

  <div class="account-aside">

    <%= image_tag avatar(@user) %>

    <h1> Welcome, <%= @user.first_name %>!</h1>

    <p><strong>First name:</strong>  <i><%= @user.first_name %></i><br>
      <strong>Last name:</strong> <i><%= @user.last_name %></i><br>
      <strong>Phone number:</strong>  <i><%= @user.phone_number %></i><br>
      <strong>Email:</strong>  <i><%= @user.email %></i></p>

      <%= link_to edit_user_path(@user) do  %>
      <div class="btn btn-primary">Edit profile info</div>
      <% end %>
    </div>

    <div class="account-main">
      <h1>My spaces</h1>
      <div class="row">
        <% @spaces.each do |space| %>
        <div class="col-lg-4 col-md-12 col-sm-12">
          <div class="card-user">
            <% if space.cover_image.file.nil? %>
            <img src=<%= asset_path("placeholder.jpg")%>>
            <% else %>
            <img src=<%=cl_image_path space.cover_image%> >
            <% end %>
            <div class="card-user-text">
              <div class="card-user-info">
                <h2><%= space.name %></h2>
                <h3><%= link_to('Edit space', edit_space_path(space)) %></h3>
              </div>
              <h2>📍<%= space.address %></h2>
            </div>
          </div>
        </div>

        <% end %>
      </div>


      <h1>Upcoming bookings</h1>
      <div class="row">
        <% @bookings.future.each do |booking| %>
        <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="card-user booking">
            <% if booking.space.cover_image.file.nil? %>
            <img src=<%= asset_path("party.jpg")%>>
            <% else %>
            <img src=<%=cl_image_path booking.space.cover_image%> >
            <% end %>
            <div class="card-user-info booking">
              <h2><strong><%= booking.space.name %></strong>, <i>on <%= booking.date %></i></h2>
              <h3>
                <%= link_to('Edit booking date', edit_space_booking_path(booking.space, booking)) %>
                <%= link_to('Delete booking', space_booking_path(booking.space, booking), method: :delete, data: {confirm: "Are you sure?"}) %></h3>
              </h3>
            </div>
          </div>
        </div>
        <% end %>

        <% unless @bookings.past.empty? %>
          <h1>Past bookings history</h1>
        <% end %>

        <% @bookings.past.each do |booking| %>
        <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="card-user booking">
            <% if booking.space.cover_image.file.nil? %>
            <img src=<%= asset_path("party.jpg")%>>
            <% else %>
            <img src=<%=cl_image_path booking.space.cover_image%> >
            <% end %>
            <div class="card-user-info booking">
              <h2><strong><%= booking.space.name %></strong>, <i>on <%= booking.date %></i></h2>
            </div>
          </div>
        </div>
        <% end %>
      </div>

    </div>

  </div>